apiVersion: apps/v1
kind: Deployment
metadata:
  name: besu-depl
  namespace: zhejiang-testnet
spec:
  selector:
    matchLabels:
      app: besu-node
  template:
    metadata:
      labels:
        app: besu-node
    spec:
      # # Set this according to your env if any
      # nodeSelector:
      #   cloud.google.com/gke-nodepool:

      initContainers:
        - name: set-zhejiang-genesis
          image: 108356037/zhejiang-besu-genesis-helper:v0.2.0
          imagePullPolicy: Always
          command:
            - cp
            - /besu.json
            - /opt/besu/genesis
          volumeMounts:
            - mountPath: /opt/besu/genesis
              name: besu-genesis

      containers:
        - name: besu
          image: hyperledger/besu:develop
          imagePullPolicy: Always
          ports:
            - containerPort: 8551 # engine rpc
            - containerPort: 8545
          command:
            - besu
            - --network-id=1337803
            - --data-path="/root/besu-datadir"
            - --genesis-file=genesis/besu.json
            - --rpc-http-enabled=true
            - --rpc-http-host=0.0.0.0
            - --rpc-http-cors-origins=*
            - --rpc-ws-enabled=true
            - --rpc-ws-host=0.0.0.0
            - --host-allowlist=*
            - --engine-host-allowlist=*
            - --engine-jwt-enabled=true
            - --engine-jwt-secret=/jwt/jwtsecret/password
            - --bootnodes=enode://691c66d0ce351633b2ef8b4e4ef7db9966915ca0937415bd2b408df22923f274873b4d4438929e029a13a680140223dcf701cabe22df7d8870044321022dfefa@64.225.78.1:30303,enode://89347b9461727ee1849256d78e84d5c86cc3b4c6c5347650093982b726d71f3d08027e280b399b7b6604ceeda863283dcfe1a01e93728b4883114e9f8c7cc8ef@146.190.238.212:30303,enode://c2892072efe247f21ed7ebea6637ade38512a0ae7c5cffa1bf0786d5e3be1e7f40ff71252a21b36aa9de54e49edbcfc6962a98032adadfa29c8524262e484ad3@165.232.84.160:30303,enode://71e862580d3177a99e9837bd9e9c13c83bde63d3dba1d5cea18e89eb2a17786bbd47a8e7ae690e4d29763b55c205af13965efcaf6105d58e118a5a8ed2b0f6d0@68.183.13.170:30303,enode://2f6cf7f774e4507e7c1b70815f9c0ccd6515ee1170c991ce3137002c6ba9c671af38920f5b8ab8a215b62b3b50388030548f1d826cb6c2b30c0f59472804a045@161.35.147.98:30303

          volumeMounts:
            - mountPath: /opt/besu/genesis
              name: besu-genesis
            - mountPath: /jwt/jwtsecret
              name: el-cl-jwt
              readOnly: true
            - mountPath: /root/besu-datadir
              name: besu-db

      volumes:
        - name: besu-genesis
          emptyDir: {}
        - name: el-cl-jwt
          secret:
            secretName: el-cl-jwt-secret
        - name: besu-db
          persistentVolumeClaim:
            claimName: besu-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: besu-pvc
spec:
  storageClassName: premium-rwo
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: Service
metadata:
  name: besu-engine-srv
spec:
  selector:
    app: besu-node
  ports:
    - port: 8551
      targetPort: 8551
